version: '3.9'

services:

  site:
    restart: always
    environment:
      MONGODB_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo/payload-${ENVIRONMENT}
    build:
      context: .
      network: nginx
      args:
        MONGODB_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo/payload-${ENVIRONMENT}
    ports:
      - "${SITE_PORT}:3000"
    depends_on:
      - mongo
    links:
      - mongo
    command: bash -c "/usr/wait-for-it.sh --timeout=0 mongo:27017 && yarn serve"
    volumes:
      - ${PAYLOAD_UPLOADS_PATH}:/usr/app/payload-uploads

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DB: payload-${ENVIRONMENT}
      ENVIRONMENT: ${ENVIRONMENT}
    ports: 
      - "27017:27017"
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ${DB_DATA_PATH}:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
      ME_CONFIG_SITE_BASEURL: /db
    depends_on:
      - mongo

networks: 
  default: 
    external: 
      name: nginx