version: '3.9'

services:

  payload:
    restart: always
    environment:
      MONGODB_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo/payload-${ENVIRONMENT}
    build: .
    ports:
      - "${PAYLOAD_PORT}:3000"
    depends_on:
      - mongo
    links:
      - mongo
    command: bash -c "/usr/wait-for-it.sh --timeout=0 mongo:27017 && npm run serve"
    volumes:
      - /usr/app/payload-${ENVIRONMENT}-uploads:/usr/app/payload-uploads

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
    depends_on:
      - mongo

networks: 
  default: 
    external: 
      name: nginx