name: DigitalOcean Droplet Deployment

on:
  push:
    branches: [staging]

jobs:
  deploy-staging:
    environment: staging
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy staging
        uses: appleboy/ssh-action@master
        env:
          MONGODB_DB: ${{secrets.MONGODB_DB}}
          MONGODB_ROOT_USERNAME: ${{secrets.MONGODB_ROOT_USERNAME}}
          MONGODB_ROOT_PASSWORD: ${{secrets.MONGODB_ROOT_PASSWORD}}
          MONGODB_USERNAME: ${{secrets.MONGODB_USERNAME}}
          MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
          PAYLOAD_SECRET: ${{secrets.PAYLOAD_SECRET}}
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          envs: MONGODB_DB,MONGODB_ROOT_USERNAME,MONGODB_ROOT_PASSWORD,MONGODB_USERNAME,MONGODB_PASSWORD,PAYLOAD_SECRET

          script: |
            rm -rf /usr/app/joshhills-cms-staging
            git clone git@github.com:joshhills/joshhills-cms.git /usr/app/joshhills-cms-staging
            chown -R root:admins /usr/app/joshhills-cms-staging
            cd /usr/app/joshhills-cms-staging
            docker-compose up -d
