name: DigitalOcean Droplet Deployment

on:
  push:
    branches: [staging]

jobs:
  deploy-staging:
    environment: staging
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy staging
        uses: appleboy/ssh-action@master
        env:
          ENVIRONMENT: staging
          PAYLOAD_PUBLIC_SERVER_URL: https://staging.joshhills.dev
          MONGODB_ROOT_USERNAME: ${{secrets.MONGODB_ROOT_USERNAME}}
          MONGODB_ROOT_PASSWORD: ${{secrets.MONGODB_ROOT_PASSWORD}}
          MONGODB_USERNAME: ${{secrets.MONGODB_USERNAME}}
          MONGODB_PASSWORD: ${{secrets.MONGODB_PASSWORD}}
          PAYLOAD_SECRET: ${{secrets.PAYLOAD_SECRET}}
          PAYLOAD_PORT: 3001
          MONGO_EXPRESS_PORT: 8081
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          envs: ENVIRONMENT,PAYLOAD_PUBLIC_SERVER_URL,MONGODB_ROOT_USERNAME,MONGODB_ROOT_PASSWORD,MONGODB_USERNAME,MONGODB_PASSWORD,PAYLOAD_SECRET,PAYLOAD_PORT,MONGO_EXPRESS_PORT

          script: |
            rm -rf /usr/app/joshhills-cms-staging
            git clone git@github.com:joshhills/joshhills-cms.git --branch staging --single-branch /usr/app/joshhills-cms-staging
            cd /usr/app/joshhills-cms-staging
            rm .env
            touch .env
            echo "PAYLOAD_PUBLIC_SERVER_URL=$PAYLOAD_PUBLIC_SERVER_URL" >> .env
            echo "PAYLOAD_PORT=$PAYLOAD_PORT" >> .env
            echo "MONGO_EXPRESS_PORT=$MONGO_EXPRESS_PORT" >> .env
            echo "ENVIRONMENT=$ENVIRONMENT" >> .env
            echo "MONGODB_ROOT_USERNAME=$MONGODB_ROOT_USERNAME" >> .env
            echo "MONGODB_ROOT_PASSWORD=$MONGODB_ROOT_PASSWORD" >> .env
            echo "MONGODB_USERNAME=$MONGODB_USERNAME" >> .env
            echo "MONGODB_PASSWORD=$MONGODB_PASSWORD" >> .env
            echo "PAYLOAD_SECRET=$PAYLOAD_SECRET" >> .env
            chown -R root:admins /usr/app/joshhills-cms-staging
            docker-compose down
            docker-compose build
            docker-compose up -d
